export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/account/login'
export const REGISTRATION_ROUTE = '/account/registration'
export const MESSAGES_ROUTE = '/messages'
export const VOICES_ROUTE = '/voices'
export const MEETS_ROUTE = '/conferences'
export const CONTACT_ROUTE = '/contacts'
export const MARKS_ROUTE = '/bookmarks'
